### ISSUE TITLE
Fix front matter of zh-cn translation of scala 3 book

### ISSUE THREAD

**Issue by bishabosha** [scala/docs.scala-lang#2559]
e.g. https://docs.scala-lang.org/zh-cn/overviews/scala3-book/why-scala-3.html

without the front matter, the pages all have the wrong url, and have no layout applied

Edit: they still need the `language` field in order to have the language dropdown

**Comment by bishabosha** [comment]
@benluo

**Comment by benluo** [comment]
I think it has been solved. I suggest to close the issue.

**Comment by bishabosha** [comment]
they are still wrong because they do not have the `language` field, so the language drop down does not appear

**Comment by benluo** [comment]
I add languages in all files in scala3-book. But they does not pass compile. How should I do?
